[package]
name = "rollatorium"
version = "0.0.1-snapshot"
edition = "2024"

[features]
fail-on-warnings = []

[dependencies]
rand = "0.9.2"
thiserror = { version = "2", default-features = false }

[dev-dependencies]
proptest = "1.8.0"
