name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main, d20port ]

jobs:
  check-rust:
    name: Rust format, clippy, build and tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install rustfmt & clippy
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy (deny warnings)
        run: cargo clippy -- -D warnings

      - name: Check
        run: cargo check --workspace --all-targets

      - name: Build (debug)
        run: cargo build --workspace --all-targets

      - name: Run tests
        run: cargo nextest run --workspace --all-targets --no-fail-fast
